#!/bin/bash

# 备注文件路径
NOTES_FILE="$HOME/.git-branch-notes"

# 添加/更新备注
if [[ $1 == "add" ]]; then
  branch_name=$2
  remark=$3
  jq --arg bn "$branch_name" --arg rk "$remark" '.[$bn] = $rk' "$NOTES_FILE" > tmp && mv tmp "$NOTES_FILE"

# 查看备注
elif [[ $1 == "show" ]]; then
  branch_name=$2
  jq -r ".[\"$branch_name\"] // \"无备注\"" "$NOTES_FILE"

# 列出所有分支备注
elif [[ $1 == "list" ]]; then
  jq -r 'to_entries[] | "\(.key): \(.value)"' "$NOTES_FILE"

# 搜索备注
elif [[ $1 == "search" ]]; then
  keyword=$2
  jq -r --arg kw "$keyword" 'to_entries[] | select(.value | contains($kw)) | "\(.key): \(.value)"' "$NOTES_FILE"
fi
